version: '2'
services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: ash -c "rm -f /app/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - "./.env.dev"
    volumes:
      - ".:/app"
    volumes_from:
      - data
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "mysql:5.7"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    volumes_from:
      - data
    ports:
      - "3306:3306"
  data:
    image: "busybox"
    volumes:
      - "db:/var/lib/mysql"
      - "bundle:/usr/local/bundle"

volumes:
  db:
    driver: local
  bundle:
    driver: local
