FROM ruby:2.5.1-alpine3.7

ENV LANG C.UTF-8

RUN apk --update add \
    build-base \
    mariadb-dev \
    tzdata \
    vim && \
    rm /usr/lib/libmysqld* && \
    rm /usr/bin/mysql* && \
    rm -rf /tmp/* /var/cache/apk/*
    
ENV ENTRYKIT_VERSION 0.4.0

RUN wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
    && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
    && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
    && mv entrykit /bin/entrykit \
    && chmod +x /bin/entrykit \
    && entrykit --symlink

WORKDIR /app

ENTRYPOINT [ \
    "prehook", "ruby -v", "--", \
    "prehook", "bundle install -j3 --quiet", "--"]
