#!/usr/bin/env bash

cp .env.dev.sample .env.dev

docker-compose build

docker-compose run --rm app bundle exec rails new . -f -d mysql -G -T --api

cp -f template/database.yml config/database.yml

docker-compose run --rm app bundle exec spring binstub --all
